theme: jekyll-theme-architect
title: Welcome to Mae Zheng's home page!
description: My name is Mae, a current sophomore at UC Berkeley majoring in Economics and Computer Science. Feel free to bookmark this to keep an eye on my project updates! Thanks:)
